[package]
name = "app_r"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_r = { path = "../CoreR" }
wrapper_r = { path = "../WrapperR" }